//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefectDataDetail
    {
        public int DefectDataDetailsId { get; set; }
        public string DefectID { get; set; }
        public string WidgetName { get; set; }
        public string DetectedStage { get; set; }
        public Nullable<System.DateTime> ReportedDate { get; set; }
        public string ReportedBy { get; set; }
        public string DefectDescription { get; set; }
        public string Status { get; set; }
        public string DefectInfectedStage { get; set; }
        public string ExpectedDetectionPhase { get; set; }
        public string DefectType { get; set; }
        public string Cause { get; set; }
        public byte[] ReviewType { get; set; }
        public string DefectSeverity { get; set; }
        public Nullable<System.DateTime> FixedOnDate { get; set; }
        public string Remarks { get; set; }
        public int PeriodId { get; set; }
        public int ProjectId { get; set; }
    
        public virtual Period Period { get; set; }
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
