//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevMetric
    {
        public int ProjectId { get; set; }
        public string ReleaseIteration { get; set; }
        public string Module { get; set; }
        public string WidgetID { get; set; }
        public string ComponentType { get; set; }
        public string WidgetType { get; set; }
        public string Complexity { get; set; }
        public string Status { get; set; }
        public Nullable<int> ComplexityPoints { get; set; }
        public Nullable<double> PlannedEffort { get; set; }
        public Nullable<double> PEFDDDevelopment { get; set; }
        public Nullable<double> PEFDDReview { get; set; }
        public Nullable<double> PEFDDRework { get; set; }
        public Nullable<double> PETDDDevelopment { get; set; }
        public Nullable<double> PETDDReview { get; set; }
        public Nullable<double> PETDDRework { get; set; }
        public Nullable<double> PECoding { get; set; }
        public Nullable<double> PECodeReview { get; set; }
        public Nullable<double> PEUTCPreparation { get; set; }
        public Nullable<double> PEUTCReview { get; set; }
        public Nullable<double> PEUTCExecution { get; set; }
        public Nullable<double> PECUTRework { get; set; }
        public Nullable<double> PEOtherRework { get; set; }
        public Nullable<double> ActualEffort { get; set; }
        public Nullable<double> AEFDDDevelopment { get; set; }
        public Nullable<double> AEFDDReview { get; set; }
        public Nullable<double> AEFDDRework { get; set; }
        public Nullable<double> AETDDDevelopment { get; set; }
        public Nullable<double> AETDDReview { get; set; }
        public Nullable<double> AETDDRework { get; set; }
        public Nullable<double> AECoding { get; set; }
        public Nullable<double> AECodeReview { get; set; }
        public Nullable<double> AEUTCPreparation { get; set; }
        public Nullable<double> AEUTCReview { get; set; }
        public Nullable<double> AEUTCExecution { get; set; }
        public Nullable<double> AECUTRework { get; set; }
        public Nullable<double> AEOtherRework { get; set; }
        public Nullable<double> TotalDEVdefects { get; set; }
        public Nullable<double> FDDReviewDefects { get; set; }
        public Nullable<double> TDDReviewDefects { get; set; }
        public Nullable<double> CodeReviewDefects { get; set; }
        public Nullable<double> UTCReviewDefects { get; set; }
        public Nullable<double> UnitTestingDefects { get; set; }
        public Nullable<double> TotalDEVDD { get; set; }
        public Nullable<double> FDDDD { get; set; }
        public Nullable<double> TDDDD { get; set; }
        public Nullable<double> CodeReviewDD { get; set; }
        public Nullable<double> UTCReviewDD { get; set; }
        public Nullable<double> UnitTestingDD { get; set; }
        public Nullable<double> TotalDEVDDR { get; set; }
        public Nullable<double> FDDDDR { get; set; }
        public Nullable<double> TDDDDR { get; set; }
        public Nullable<double> CodeReviewDDR { get; set; }
        public Nullable<double> UTCReviewDDR { get; set; }
        public Nullable<double> UnitTestingDDR { get; set; }
        public Nullable<double> TotalDEVProductivity { get; set; }
        public Nullable<double> FDDProductivity { get; set; }
        public Nullable<double> TDDProductivity { get; set; }
        public Nullable<double> CodingProductivity { get; set; }
        public Nullable<double> UTProductivity { get; set; }
        public Nullable<System.DateTime> PlannedStartdate { get; set; }
        public Nullable<System.DateTime> PlannedEnddate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<int> ProjectReleaseId { get; set; }
    
        public virtual ProjectReleaseMaster ProjectReleaseMaster { get; set; }
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
