//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EffortDetail
    {
        public int EffortId { get; set; }
        public Nullable<int> ComponentId { get; set; }
        public string ComponentTypeCode { get; set; }
        public string ComplexityCode { get; set; }
        public string TaskTypeCode { get; set; }
        public Nullable<int> BaselineEffort { get; set; }
        public Nullable<int> ActualEffort { get; set; }
        public string StatusCode { get; set; }
        public string CMMIRollUpCode { get; set; }
        public Nullable<System.DateTime> ScheduledStartDate { get; set; }
        public Nullable<System.DateTime> ScheduledEndDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public string ProjectId { get; set; }
        public Nullable<int> ReleaseId { get; set; }
        public string ModuleName { get; set; }
        public string ComponentName { get; set; }
        public string ReviewTypeCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ProjectReleaseId { get; set; }
        public Nullable<int> MonthId { get; set; }
        public string WidgetType { get; set; }
        public int ProjectMasterId { get; set; }
    
        public virtual MonthMaster MonthMaster { get; set; }
        public virtual ProjectMaster ProjectMaster { get; set; }
        public virtual ProjectReleaseMaster ProjectReleaseMaster { get; set; }
    }
}
