//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MetricMaster()
        {
            this.ProjectMetricAssociations = new HashSet<ProjectMetricAssociation>();
        }
    
        public int MetricMasterID { get; set; }
        public string MetricCategoryCode { get; set; }
        public string MetricCategoryDescription { get; set; }
        public string MetricSubCategoryCode { get; set; }
        public string MetricSubCategoryDescription { get; set; }
        public string MetricTypeCode { get; set; }
        public string MetricTypeDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string MetricsDescription { get; set; }
        public string FormulaDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectMetricAssociation> ProjectMetricAssociations { get; set; }
    }
}
