//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreferredReportMetricsAssociation
    {
        public int PreferredReportMetricsAssociationID { get; set; }
        public Nullable<int> ProjectReleaseID { get; set; }
        public Nullable<int> MonthId { get; set; }
        public Nullable<int> MetricAssociationID { get; set; }
        public Nullable<int> UserReportAssociationID { get; set; }
    }
}
