//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectWidgetDetail
    {
        public int ProjectWidgetDetailID { get; set; }
        public int ProjectID { get; set; }
        public string WidgetName { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
