//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceTable
    {
        public int ReferenceTableId { get; set; }
        public string ReferenceTableName { get; set; }
        public string ReferenceCode { get; set; }
        public string ReferenceValue { get; set; }
    }
}
