//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadDetail
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int MonthId { get; set; }
        public int ReleaseId { get; set; }
        public System.DateTime UploadedDate { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
